version: "3.8"
services:
    bot:
        image: textfacesbot:latest
        container_name: "textfacesbot"
        volumes:
          - './data:/app/data'
        environment:
          - BOT_TOKEN=123456:AaBbCcDdEeFfGg
        restart: unless-stopped
